config/routes.rb
Sernobi::Application.routes.draw do
  get "welcome/index"
  get "welcome/about"

  root to: "welcome#index"

  resources :comments
  resources :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def my_name
  	"Muzaparoff"
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sernobi Heroku</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<ul class="nav nav-tabs">
			<li><%= link_to "Home", welcome_index_path %></li>
			<li><%= link_to "About", welcome_about_path %></li>
		</ul>
		<%= yield %>
	</div>
</body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/welcome/about.html.erb
<h1>Welcome to Sernobist</h1>
<p>This is the home page for Sernobist.</p>

app/views/welcome/index.html.erb
<h1>About Shinobicit</h1>
<p id="index-title">This is the home page for Shinobicit.</p>
<div class="posts">Post 1 goes here.</div>
<div class="posts">Post 2 goes here.</div>

<section>I am the content in a section element.</section>
<p>Created by: <%= my_name %></p>